version: "3.8"

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /srv/docker/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - /srv/docker/traefik/dynamic:/etc/traefik/dynamic:ro
      - /srv/docker/traefik/acme.json:/acme.json
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
    networks:
      - internal
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}

  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    networks:
      - internal

  tunnel:
    image: cloudflare/cloudflared
    container_name: cloudflared-tunnel
    restart: unless-stopped
    command: tunnel run
    networks:
      - internal
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "53:53/tcp"       # DNS TCP
      - "53:53/udp"       # DNS UDP
      - "3000:3000"       # Setup
      - "8080:80/tcp"     # Admin Dashboard
    volumes:
      - /srv/docker/adguard/data/work:/opt/adguardhome/work
      - /srv/docker/adguard/data/conf:/opt/adguardhome/conf

networks:
  internal:
    external: true
